---
- name: Deploy GitLab
  hosts: gitlab
  tasks:
  - name: Configure certificates
    ansible.builtin.include_role:       
      name: "demo.cloud.certbot53"

  - name: Configure GitLab
    ansible.builtin.include_role:       
      name: "demo.cloud.gitlab"

