---
- name: Deploy GitLab Runner
  gather_facts: false
  hosts: "{{ gitlab_runner_host_name | default('gitlab-runner') }}"
  tasks:
    - name: Wait for host to be listening for SSH connections
      ansible.builtin.wait_for:
        port: 22
        host: "{{ hostvars[ansible_host]['ansible_ssh_host']|default(ansible_host)|default(inventory_hostname) }}"
        search_regex: OpenSSH
        delay: 10
      delegate_to: localhost

    - name: Run setup
      ansible.builtin.setup:

    - name: Configure GitLab runner
      ansible.builtin.include_role:
        name: "external.geerlingguy.docker"
        apply:
          become: true

    - name: Install python3-pip dependency  
      ansible.builtin.package:
        name: python3-pip
        state: present
      become: true

    - name: Install python-gitlab pip dependency  
      ansible.builtin.pip:
        name: python-gitlab
        state: present

# create auth token
# register runner
