---
- name: Deploy GitLab
  hosts: gitlab
  tasks:
  - name: List all hosted zones
    amazon.aws.route53_info:
      query: hosted_zone
    register: hosted_zones
    delegate_to: localhost

  - name: debug
    ansible.builtin.debug:
      msg: "{{ hosted_zones}}"
  - name: debug
    ansible.builtin.debug:
      msg: "{{ hosted_zones[0] }}"

  - name: debug
    ansible.builtin.debug:
      msg: "{{ hosted_zones[0].Name }}"

  - name: Set hostname
    ansible.builtin.set_fact:
      hostname: "gitlab.{{ hosted_zones[0].Name }}"
      zone: "{{ hosted_zones[0].Name }}"
      msg: "{{ hosted_zones[0].Name }}"

  - name: Configure certificates
    ansible.builtin.include_role:       
      name: "demo.cloud.certbot53"
    vars:
      acme_env: staging

  - name: Configure certificates
    ansible.builtin.include_role:       
      name: "demo.cloud.certbot53"
    vars:
      acme_env: production
      acme_directory: "https://acme-v02.api.letsencrypt.org/directory"

  - name: Configure GitLab
    ansible.builtin.include_role:       
      name: "demo.cloud.gitlab"

