---
- name: Deploy AWS stack
  hosts: localhost
  vars:
    controller_components:
      - job_launch
      - workflow_launch

    controller_workflow_launch_jobs:
      - name: Deploy Cloud Stack in AWS
        wait: true
        extra_vars:
          create_vm_aws_region: "us-east-2"
          create_vm_aws_owner_tag: "gitlab"
          vm_environment: "Prod"
          aws_public_key: "{{ gitlab_ssh_public_key }}"
          email: "git@gitlab.exmaple.com"

    controller_job_launch:
      - name: Cloud / AWS / Create VM
        wait: true
        extra_vars:
          vm_blueprint: "rhel9"
          create_vm_aws_region: "us-east-2"
          create_vm_vm_name: gitlab
          create_vm_vm_owner: "gitlab"
          create_vm_vm_deployment: "gitlab"
          create_vm_vm_environment: "Prod"
          create_vm_aws_keypair_name: aws-test-key
          create_vm_aws_securitygroup_name: aws-test-sg
    
      - name: Cloud / AWS / Create VM
        wait: true
        extra_vars:
          vm_blueprint: "rhel9"
          create_vm_aws_region: "us-east-2"
          create_vm_vm_name: gitlab-runner
          create_vm_vm_owner: "gitlab"
          create_vm_vm_deployment: "gitlab"
          create_vm_vm_environment: "Prod"
          create_vm_aws_keypair_name: aws-test-key
          create_vm_aws_securitygroup_name: aws-test-sg
  tasks:
    - name: Demo Components
      ansible.builtin.include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      when:
        - controller_components | d("") | length > 0


- name: GitLab application deployment
  hosts: gitlab
  vars:
  tasks:
    - name: Configure certificates
      ansible.builtin.include_role:
        name: "demo.cloud.certbot53"

    - name: Configure gitlab
      ansible.builtin.include_role:
        name: "demo.cloud.gitlab"

