---
- name: Deploy GitLab
  hosts: gitlab
  vars:
    hostname: gitlab
  tasks:
  - name: Install package depends
    become: true
    ansible.builtin.package:
      name: ['python3-cryptography', 'python3-pip']
      state: present

  - name: install python depends
    ansible.builtin.pip:
     name: ['boto3', 'botocore']
     state: present

  - name: Query route53 for all hosted zones
    amazon.aws.route53_info:
      query: hosted_zone
    register: r53
    delegate_to: localhost

  - name: Set hostname
    ansible.builtin.set_fact:
      route53_zone: "{{ r53.HostedZones[0].Name[:-1] }}"

  - name: debug
    ansible.builtin.debug:
      msg: "{{ route53_zone }}"

  - name: Configure certificates
    ansible.builtin.include_role:       
      name: "demo.cloud.certbot53"
    vars:
      acme_env: staging

  - name: Configure certificates
    ansible.builtin.include_role:       
      name: "demo.cloud.certbot53"
    vars:
      acme_env: production
      acme_directory: "https://acme-v02.api.letsencrypt.org/directory"

  - name: Configure GitLab
    ansible.builtin.include_role:       
      name: "demo.cloud.gitlab"

