---
# This runs after gitlab has finished deploying
- name: Configure gitlab runner 
  gather_facts: false
  hosts: "{{ gitlab_runner_host_name | default('gitlab-runner') }}"
  tasks:
    - name: Wait for gitlab API to be up and healthy
      ansible.builtin.wait_for:
        port: 443
        host: "{{ gitlab_fqdn }}"
        delay: 10
      delegate_to: localhost

# create auth token
# register runner
