---
- name: Configure gitlab runner 
  gather_facts: false
  hosts: "{{ gitlab_runner_host_name | default('gitlab-runner') }}"
  tasks:
    - name: Read in initial gitlab root password
      ansible.builtin.slurp:
        src: /etc/gitlab/initial_root_password
      register: initial_root_file
      delegate_to: "{{ gitlab_host_name | default('gitlab') }}"
      become: true

    - name: Wait for gitlab API to be up and healthy
      ansible.builtin.wait_for:
        port: 443
        host: "{{ gitlab_fqdn }}"
        delay: 10
      delegate_to: localhost

    - name: Set intermediary
      ansible.builtin.set_fact:
        password_from_file: "{{ initial_root_file.content  | b64decode }}"

    - name: Debug output
      ansible.builtin.debug:
        msg: "{{ password_from_file }}"

    - name: Debug output
      ansible.builtin.debug:
        msg: "{{ password_from_file | from_yaml }}"

    - name: Debug output
      ansible.builtin.debug:
        msg: "{{ password_from_file | from_yaml | map('extract', 'Password') }}"

# create auth token
# register runner
