---
- name: Check required variables
  ansible.builtin.assert:
    that:
      - cb53_hostname | length > 0
      - cb53_route53_zone | length > 0
      - cb53_cert_dir | length > 0

- name: Build top level directory
  ansible.builtin.file:
    path: "{{ cert_path }}"
    state: directory
    mode: '0700'

- name: Generate account private key
  community.crypto.openssl_privatekey:
    path: "{{ account_privatekey }}"

- name: Generate our server private key
  community.crypto.openssl_privatekey:
    path: "{{ privatekey_path }}"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ privatekey_path }}"
    common_name: "{{ fqdn }}"

- name: Create a challenge for `fqdn` using a account key file.
  community.crypto.acme_certificate:
    terms_agreed: true
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ account_privatekey }}"
    account_email: "{{ account_email }}"
    src: "{{ csr_path }}"
    cert: "{{ crt_path }}"
    challenge: dns-01
    acme_directory: "{{ acme_directory }}"
    # Renew if the certificate is at least 30 days old
    remaining_days: 60
  register: challenge_output

- name: Debug challenge_output
  debug:
    msg: "{{ challenge_output }}"

- name: fulfill challenge in route53
  amazon.aws.route53:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') | default(aws_access_key) }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') | default(aws_secret_key) }}"
    zone: "{{ cb53_route53_zone }}"
    record: "{{ challenge_output.challenge_data[fqdn]['dns-01'].record }}"
    type: TXT
    ttl: 60
    state: present
    wait: yes
    # Note: route53 requires TXT entries to be enclosed in quotes
    value: "{{ challenge_output.challenge_data[fqdn]['dns-01'].resource_value | regex_replace('^(.*)$', '\"\\1\"') }}"
    overwrite: yes
  when: 
    - challenge_output is changed 
    - fqdn in challenge_output.challenge_data

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  community.crypto.acme_certificate:
    terms_agreed: yes
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ account_privatekey }}"
    account_email: "{{ account_email }}"
    src: "{{ csr_path }}"
    cert: "{{ crt_path }}"
    fullchain: "{{ fullchain_path }}"
    chain: "{{ chain_path }}"
    challenge: dns-01
    acme_directory: "{{ acme_directory }}"
    remaining_days: 60
    data: "{{ challenge_output }}"
  when: challenge_output is changed

- name: Set stats for private key and full chain
  ansible.builtin.set_stats:
    data:
      certbot53_public_path: "{{ fullchain_path }}"
      certbot53_private_path: "{{ privatekey_path }}"
  when: challenge_output is changed
