---
- name: Expose job paths
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    ansible_connection: local
  tasks:
    - name: Add 
      ansible.controller.settings:
        name: "AWX_ISOLATION_SHOW_PATHS"
        value: 
          - "/var/lib/awx/projects/:/var/lib/awx/projects/:RW"
          - "/etc/pki/ca-trust:/etc/pki/ca-trust:O"
          - "/usr/share/pki:/usr/share/pki:O"

- name: Build controller dependencies for low-code Automation
  hosts: localhost
  become: true
  vars:
    ansible_connection: local
  tasks:
    - name: Initialize path 'manual' projects
      ansible.builtin.file:
        dest: /var/lib/awx/projects
        state: directory

    - name: Create project folder
      ansible.builtin.file:
        dest: /var/lib/awx/projects/low_code
        state: directory

    - name: Create collections folder
      ansible.builtin.file:
        dest: /var/lib/awx/projects/low_code/collections
        state: directory

    - name: Template ansible.cfg
      ansible.builtin.template:
        dest: /var/lib/awx/projects/low_code/ansible.cfg
        src: ansible.cfg.j2

    - name: Template requirements.yml
      ansible.builtin.copy:
        dest: /var/lib/awx/projects/low_code/requirements.yml
        content: "{{ required_collections | to_yaml }}"

    - name: Pull collections
      ansible.builtin.command: ansible-galaxy install -r requirements.yml -p collections/
      args:
        chdir: /var/lib/awx/projects/low_code/
      
    - name: Template playbook
      ansible.builtin.template:
        dest: /var/lib/awx/projects/low_code/playbook.yml
        src: playbook.yml.j2

- name: Build AAP resources for low-code Ansible
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    ansible_connection: local
  tasks:
    - name: Create AAP project
      ansible.controller.project:
        name: "Low-Code Automation"
        local_path: "low_code"
        organization: "Default"
        scm_type: manual
        state: present

    - name: Create Job Template
      ansible.controller.job_template:
        name: "Run Low-Code Automation Job"
        job_type: "run"
        organization: "Default"
        project: "Low-Code Automation"
        inventory: "Demo Inventory"
        playbook: "playbook.yml"
        credentials: 
          - "Demo Credential"
        survey_enabled: yes
        survey_spec:
          name: ''
          description: ''
          spec:
            - question_name: Server Name or Pattern
              type: text
              variable: _hosts
              required: true
