---
- name: Provision OCP-CNV VM with provided definition
  hosts: localhost
  tasks:
    - name: Define resources
      redhat.openshift.k8s:
        wait: true
        state: "{{ instance_state | default('present') }}"
        definition: "{{ vm_definition }}"

    - name: Wait for VM to be running
      redhat.openshift_virtualization.kubevirt_vm_info:
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
        wait: true
        wait_timeout: 240
