- name: Create a new user
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  gather_facts: false
  tasks:
    - name: "Add the user {{ _new_user }}"
      ansible.builtin.user:
        name: "{{ _new_user }}"
        create_home: yes
        password: "{{ _password | password_hash('sha512', 'new-user-hash') }}"
        groups: "{{ _groups | default(omit) }}"
