---
- name: Configure SSH Server
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  tasks:
    - name: Copy old sshd config
      ansible.builtin.copy:
        src: /etc/ssh/sshd_config
        dest: /tmp/sshd_config.bak
        remote_src: true

    - name: Try to configure sshd
      block:
      - name: "Ensure line in file"
        ansible.builtin.lineinfile:
          path: /etc/ssh/sshd_config
          regexp: "^{{ item.key }}"
          line: "{{ item.key }} {{ item.value }}"
        loop: "{{ _sshd_config | from_yaml | dict2items }}"
        notify: "Restart sshd"

      - name: "Flush handlers"
        meta: flush_handlers

      rescue:
      - name: Restore sshd config
        ansible.builtin.copy:
          src: /tmp/sshd_config.bak
          dest: /etc/ssh/sshd_config
          remote_src: true
        notify: "Restart sshd"

      - name: "Flush handlers"
        meta: flush_handlers

  handlers:
    - name: "Restart sshd"
      ansible.builtin.service:
        name: sshd
        state: restarted
